
import React, { useState } from 'react';
import { geminiService } from '../services/geminiService';
import { TeacherSchedule } from '../types';
import { Calendar, Loader2, Download, Plus, BookOpen, Printer } from 'lucide-react';

const TeacherTools: React.FC = () => {
  const [topic, setTopic] = useState('');
  const [weeks, setWeeks] = useState(4);
  const [loading, setLoading] = useState(false);
  const [schedule, setSchedule] = useState<TeacherSchedule[] | null>(null);

  const handleGenerate = async () => {
    if (!topic) return;
    setLoading(true);
    try {
      const data = await geminiService.generateSchedule(topic, weeks);
      setSchedule(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="max-w-5xl mx-auto space-y-8">
      <header className="no-print">
        <h2 className="text-3xl font-bold text-slate-900">Curriculum Planner</h2>
        <p className="text-slate-500">Generate structured teaching schedules in seconds.</p>
      </header>

      <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm no-print">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 items-end">
          <div className="md:col-span-2">
            <label className="block text-sm font-bold text-slate-700 mb-2">Subject / Topic</label>
            <input 
              type="text" 
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="e.g. Introduction to Neural Networks"
              className="w-full px-5 py-3 border border-slate-200 rounded-xl focus:ring-4 focus:ring-blue-100 outline-none"
            />
          </div>
          <div>
            <label className="block text-sm font-bold text-slate-700 mb-2">Timeline (Weeks)</label>
            <input 
              type="number" 
              min="1" 
              max="16"
              value={weeks}
              onChange={(e) => setWeeks(parseInt(e.target.value))}
              className="w-full px-5 py-3 border border-slate-200 rounded-xl focus:ring-4 focus:ring-blue-100 outline-none"
            />
          </div>
          <button 
            onClick={handleGenerate}
            disabled={loading || !topic}
            className="bg-blue-600 hover:bg-blue-700 disabled:bg-slate-300 text-white font-bold py-3 px-6 rounded-xl transition-all flex items-center justify-center gap-2"
          >
            {loading ? <Loader2 className="animate-spin w-5 h-5" /> : <Calendar className="w-5 h-5" />}
            Generate Schedule
          </button>
        </div>
      </div>

      {schedule && (
        <div id="schedule-print-zone" className="grid grid-cols-1 gap-6 pb-20">
          <div className="hidden print:block mb-8 border-b-2 border-slate-900 pb-4">
            <h1 className="text-3xl font-bold text-slate-900">{topic} - Teaching Schedule</h1>
            <p className="text-slate-500 mt-2">Generated by LearnAI Adaptive Platform • {new Date().toLocaleDateString()}</p>
          </div>

          {schedule.map((item, idx) => (
            <div key={idx} className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden flex flex-col md:flex-row print-container">
              <div className="bg-blue-600 md:w-48 p-8 flex flex-col items-center justify-center text-white">
                <span className="text-xs font-bold uppercase tracking-widest opacity-80">Week</span>
                <span className="text-5xl font-black">{item.week.replace(/\D/g,'') || (idx+1)}</span>
              </div>
              <div className="flex-1 p-8 grid grid-cols-1 md:grid-cols-2 gap-8">
                <div>
                  <h4 className="text-xs font-bold text-blue-600 uppercase tracking-widest mb-2">Core Topic</h4>
                  <h3 className="text-xl font-bold text-slate-900 mb-4">{item.topic}</h3>
                  <div className="space-y-2">
                    <h5 className="text-sm font-bold text-slate-500">Learning Objectives</h5>
                    <ul className="list-disc list-inside text-sm text-slate-600 space-y-1">
                      {item.objectives.map((obj, i) => <li key={i}>{obj}</li>)}
                    </ul>
                  </div>
                </div>
                <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
                  <h4 className="text-xs font-bold text-blue-600 uppercase tracking-widest mb-3 flex items-center gap-2">
                    <BookOpen className="w-3 h-3" />
                    Class Activities
                  </h4>
                  <ul className="space-y-3">
                    {item.activities.map((act, i) => (
                      <li key={i} className="flex gap-3 text-sm text-slate-700">
                        <Plus className="w-4 h-4 text-blue-500 flex-shrink-0" />
                        {act}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          ))}
          <button 
            onClick={handlePrint}
            className="flex items-center justify-center gap-2 text-slate-400 hover:text-slate-600 transition-colors py-8 font-semibold no-print"
          >
            <Printer className="w-5 h-5" />
            Export as PDF / Print Schedule
          </button>
        </div>
      )}
    </div>
  );
};

export default TeacherTools;
